connect lb;
create graph LBTest;
use LBTest;

create node Person;
create edge Knows(Person -> Person);

insert N(1,"Person");
insert N(2,"Person");
insert E(10,1,2,"Knows");

CREATE virtual VIEW FriendsLB ON g (
  MATCH (a:Person)-[x:Knows]->(b:Person)
); 

MATCH (a:Person)-[x:Knows]->(b:Person) FROM g RETURN (a),(b),(x);

quit;

